install:
  - rm -rf public || exit 0
  - mkdir ~/_bin
  - wget https://github.com/gohugoio/hugo/releases/download/v0.38/hugo_0.38_Linux-64bit.tar.gz -O hugo.tgz
  - tar xfv hugo.tgz -C ~/_bin
  - rm hugo.tgz ~/_bin/*.md
  - export PATH=$HOME/_bin:$PATH

script:
  - hugo version
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: "/public"
  target_branch: master
  on:
    branch: source
    