baseURL = "https://www.xlhaw.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Leon Xiao's Blog"
theme = "dream-plus"

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

googleAnalytics = "UA-112332904-1"
disqusShortname = "xlhaw"
enableRobotsTXT = true

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
	author = "Leon Xiao"
	description = "Just a random blog for random stuff, mostly tech-related."
	avatar = "/images/myavatar.jpg"
	motto = "A keen maker, programmer and an Instructables author."
	enableToc = true
	enableShareCard = true

	favicon = "/images/favicon.ico" 
  	
  	#Background settings
	enableColorBG= true

	#Post-displaying Settings
	enableTags = true
	enableCategories = true

	#Cards or posts shown per page
	itemsPerPage = 4

	#Set whether you're hosting "cards" or "post"
	contentType = "post"

	#Enable Twitter Emoji
	twitterEmoji=true
	
[social]
	email = "i@xlhaw.com"
	github = "xlhaw"
	linkedin = "xlhaw"
	twitter = "xlhaw" 
	siteStartYear = 2018