---
title: "R & RMarkdown Quick Start"
author: "Leon Xiao"
date: '2019-01-12'
cover: /images/default1.jpg
description: null
draft: true
lastmod: '2019-01-13T17:54:26+08:00'
slug: rmad-rmd
tags:
- R
- R Markdown
categories:
- Programming
- Notes
---

# R & RMarkdown, A Short Note

I knew the R language long time ago. At around 2009, I started to learn the basics of Maple and MATLAB While I never really looked into the R. Even though I'm still a layman in programming. What brings me back to R&Rmarkdown is that I found it extremly convenient to write and elaborate ideas in markdown. And Rmarkdown makes writing more efficient and plotting more seamless. Since I also began my journey to data science in 2018, R is undoubtly a powerful alternative to python/pandas.So here we go.


## R Vs Pandas/Python

  

| R                                               | Python                        |
| ----------------------------------------------- | ----------------------------- |
| library() source(.R)                            | import                        |
| getwd()                                         | os.getcwd()                   |
| setwd('/')                                      | os.chdir('\\')                |
| df <- read.csv(path)                            | df=pd.read_csv(path)          |
| cor(df[,c('a','b')])                            | df[['a','b']].corr()          |
| summary(df$col)                                 | df.col.describe()             |
| %in%                                            | isin()                        |
| length(df$col)                                  | df.col.shape                  |
| subset(df,a=='a'&b='b')                         | df[(df.a=='a')&(df.b=='b')]   |
| ?module ,  ??function                           | help(module)                  |
| merged <- merge(df1, df2, by='id')  /by.x, by.y | merged=df1.merge(df2,on='id') |
| concat=rbind(df1,df2)                           | concat=([df1,df2])            |
|                                                 |                               |
| sum/unique                                      | sum/unique                    |



### Data Structure

c/list/array/matrix/factor/data.frame/data.table

factor() behave like set() in python

### Control Flow
function(input){}

for (indx in start:end){}

if (cond) {} else {}

ifelse(cond,ifyes,ifno)

switch(,do1,do2,...)



### Miscellaneous
apply(data,*arg,function),lapply,mapply
apply/t/s/l/m


Plotting:
data() -> barplot() 

```{r pressure, echo=FALSE}
plot(pressure)
```

misc
debug/stop/warning/message/traceback/browser



## R Markdown & Blogdown

n

### Structure:

> index.Rmd
> 01-intro.Rmd
> ...
> 05-end.Rmd

not numbered heading
```# Preface {-}```
part title
```# (PART) Part I {-} ```
all chapters after (APPENDIX) are appendices
```# (APPENDIX) Appendix {-} ```



### Blogdown

> blogdown:::new_post_addin()
> blogdown:::insert_image_addin()
> blogdown:::serve_site()
> new_post(title='') ~ new_content(path = 'post/')
> serve_site()



### Knitr

> knitr::kable(caption,booktabs)
> knitr::include_app()
> knitr::include_url()

### Bookdown
> bookdown::render_book()
> render_book()
> preview_chapter()
> serve_book()

## Useful R packages

There's no doubt that, the is to scatter.

```R
install.packages('plotly')
install.packages('blogdown')
install.packages('rmarkdown')
install.packages('md2mm')
install.packages('mindr')
install.packages('pinyin')
install.packages('knitr')
install.packages('tidyverse')
install.packages("shinydashboard")
install.packages("flexdashboard")
install.packages('e1071')
install.packages('car')
install.packages('MASS')
install.packages('lmtest')
install.packages('mgcv')
install.packages('rpart')
install.packages('caret')
install.packages('party')
install.packages('class')
install.packages('klaR')
install.packages('neuralnet')
install.packages('nnet')
install.packages('rminer')
install.packages('ROCR')
install.packages('pROC')
install.packages('glm')
install.packages('adabag')
install.packages('ipred')
install.packages('olsrr')
install.packages('alphavantager')
install.packages('mapsapi')
install.packages('RGtk2')
install.packages('rattle')
install.packages('Rcharts')
install.packages('readtext')
install.packages('rgl')
install.packages('ggplotgui')
install.packages('lattice')
install.packages('wordcloud2')
install.packages('SMM')
install.packages('BayesRS')
install.packages('jiebaR')
install.packages('tm')
install.packages('snowball')
install.packages('gsl')
install.packages('signal')
install.packages('bayesm')
install.packages('BACCO')
install.packages('apcluster')
install.packages('evclust')
install.packages('kernlab')
install.packages('RSNNS')
install.packages('kknn')
install.packages('C50')
install.packages('arules')
install.packages('cluster')
install.packages('ipred')
install.packages('dendextend')
install.packages('fpc')
install.packages('mlbench')
install.packages('mclust')
install.packages('seriation')
install.packages('png')
install.packages('arulesViz')
install.packages('arulesSequences')
install.packages('FSelector')
install.packages('igraph')
install.packages('bmp')
install.packages('vegan')
install.packages('RnavGraphImageData')
source('http://bioconductor.org/biocLite.R')
biocLite('graph')
install.packages('quantmod')
install.packages('shiny')
```